
const types = {
    CHECK_NEXT_PAGE: 'CHECK_NEXT_PAGE',
    SET_RESULT: 'SET_RESULT',
    CHANGE_DATE: 'CHANGE_DATE',
    PAGINATION: 'PAGINATION',
    DATE: 'DATE',
    CHANGE_DATE: 'CHANGE_DATE',
    NEXT_PAGE: 'NEXT_PAGE',
    LAST_PAGE: 'LAST_PAGE',
    CHANGE_PAGE: 'CHANGE_PAGE',
    CHANGE_PER_PAGE: 'CHANGE_PER_PAGE',
    GET_TOKEN: 'GET_TOKEN',
    SET_CHECK_NEXT_PAGE: 'SET_CHECK_NEXT_PAGE'
}

export default types
